#!/usr/bin/env bash

set -euo pipefail # stop, when error occurs, even within pipes

function help:secrets-missing() {
  echo "secrets.env not found!"
  echo "Try:"
  echo "  cp example-secrets.env secrets.env"
}

[ -f secrets.env ] && . secrets.env || (help:secrets-missing >&2 && exit 1)
clojure -M:test "$@"
